### ISSUE TITLE
sjs + mootools

### ISSUE THREAD

**Issue by lavmax** [mhansen/antinode#11]
Hi,
have you tried to use ss mootools in sjs files? It doesn't work for me and I can't figure out why.

**Comment by mhansen** [comment]
Hey, no I haven't. How exactly does it not work - do you get an error? Does the server crash? Does it work on vanilla node.js?

**Comment by lavmax** [comment]
Yes, it works if I make require(./mootools) in antinode.js, but adding this to any sjs file just ignored. No err messages is got. 
It's easy to check if mootools executed correctly on any native object which mootools extends, e.g. JSON should get two additional methods but it is not.
I suppose that this is because of sandbox, but I'm not sure.
