### ISSUE TITLE
What node version is expected?

### ISSUE THREAD

**Issue by iamnoah** [mhansen/antinode#6]
Would be good if the readme noted what version(s) of node the code is developed for, to sort out incompatibility issues.

**Comment by mhansen** [comment]
Closed by adb8d1f327010ebcff55c694de95fe3ffac2a354

**Comment by iamnoah** [comment]
Readme is out of date. 0.1.97 has no pump method.

**Comment by mhansen** [comment]
Thanks! Fixed in e40b1134c16ab193e887d6ca41a05a7a46b35144
