### ISSUE TITLE
Should redirect when directory is missing trailing / to fix relative urls

### ISSUE THREAD

**Issue by iamnoah** [mhansen/antinode#7]
GIven web root:

```
foo/
foo/foo.png
foo/index.html
```

index.html containing: &lt;img src="foo.png">

If I browse to /foo, the image will fail to load. I have to go to /foo/

**Comment by mhansen** [comment]
Thanks for the report! I'll start working on this now. I'm thinking 302 Found is the right way to go here

**Comment by mhansen** [comment]
Just patched in 0a29a7945f237a55ad84ce52078bda3575719ba7. Let me know if I missed anything :)
